### ISSUE TITLE
Decisión del proyecto y Características

### ISSUE THREAD

**Issue by GustavoAlonsoValleBustamante** [UPT-FAING-EPIS/proyecto-smi-2023-ii-u1-appcrafters#1]

**Comment by Moises195** [comment]
[Proyecto de Soluciones Moviles.pptx](https://github.com/UPT-FAING-EPIS/proyecto-smi-2023-ii-u1-appcrafters/files/12707462/Proyecto.de.Soluciones.Moviles.pptx)

**Comment by Moises195** [comment]
[Proyecto de Soluciones Moviles.pptx](https://github.com/UPT-FAING-EPIS/proyecto-smi-2023-ii-u1-appcrafters/files/12707463/Proyecto.de.Soluciones.Moviles.pptx)
